#!/bin/bash
set -eux

FORCE_FLAG=''
print_usage() {
  printf "Usage: Only -f(=force) option is allowed."
}
while getopts 'f' flag; do
  case "${flag}" in
    f) FORCE_FLAG='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd .. >/dev/null 2>&1 && cd .. >/dev/null 2>&1 && pwd )"
source "${DOTFILES}/config"

if [ ! -z ${FORCE_FLAG} ];then
    sudo apt update
    sudo apt upgrade
fi
cat packages | grep "^[^#;]" | xargs sudo apt install -y

# git
source "${DOTFILES}/bin/git/config"

# VSCode
VSCODE_USER_SETTING=~/.config/Code\ -\ OSS/User
if [ -e "${VSCODE_USER_SETTING}" ];then
    ln -f "${DOTFILES}/vscode/User/keybindings.json" "${VSCODE_USER_SETTING}/keybindings.json"
    ln -f "${DOTFILES}/vscode/User/settings.json" "${VSCODE_USER_SETTING}/settings.json"
fi
