#!/bin/sh

set -euxo

DOTFILES=$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )
. "$DOTFILES/lib/colors"

SSH_DIR="$HOME/.ssh"
mkdir -p "$SSH_DIR"
SSH_KEY="$SSH_DIR/id_rsa"
SSH_KEY_PUB="$SSH_DIR/id_rsa.pub"

KEY_COMMENT="$(uname -n)"

if [ ! -f "$SSH_KEY" ] && [ ! -f "$SSH_KEY_PUB" ] ;then
    ssh-keygen -t rsa -b "${SSH_KEY_SIZE_BIT:-4096}" -C "$KEY_COMMENT" -N "${PASSPHRASE:-}" -f "$SSH_KEY"
fi

SSH_KEY_PUB_CONTENT=$(cat "$SSH_KEY_PUB" | awk '{print $1" "$2}')
CREATED_KEYS=$(curl -i https://api.github.com/users/$GITHUB_USER/keys)

if echo "$CREATED_KEYS" | grep -q "$SSH_KEY_PUB_CONTENT" ;then
    echo "${GREEN}ssh key was already added!!!${NO_COLOR}"
else
    curl \
    -u "$GITHUB_USER:$GITHUB_PERSONAL_TOKEN" \
    -X POST \
    -d "{\"title\": \"$KEY_COMMENT\",\"key\": \"$SSH_KEY_PUB_CONTENT\"}" \
    https://api.github.com/user/keys
fi

if ssh -i "$SSH_KEY" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -T git@github.com 2>&1 | grep -q authenticated; then
    echo "${GREEN}ssh key was successfully added!!!${NO_COLOR}"
else
    echo "Adding ssh key was ${RED}failed${NO_COLOR}. Please check https://github.com/settings/keys"
fi

# References
# https://developer.github.com/v3/users/keys/#create-a-public-key
