cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "aws/tap"
tap "graalvm/tap"
tap "heroku/brew"
tap "xhiroga/aws-session-manager-plugin"
tap "xhiroga/tap"
tap "mongodb/brew"
tap "TylerBrock/saw"
tap "weaveworks/tap"

brew "apache-spark"
brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"
brew "grep"

brew "arp-scan"
brew "ansible"
brew "anyenv"
brew "aws-cdk"
brew "awscli"
brew "awslogs"
brew "aws-session-manager-plugin"
brew "bash"
brew "bash-completion"
brew "chamber"
brew "csvkit"
brew "deno"
brew "dep"
brew "exa"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "go"
brew "gradle"
brew "graphviz"
brew "gnupg"
brew "helm"
brew "heroku"
brew "jq"
brew "kotlin"
brew "kubernetes-cli"
brew "lazydocker"
brew "mas"
brew "maven"
brew "mongodb-community"
brew "mongodb-database-tools"
brew "node"
brew "nvm"
brew "peco"
brew "pipenv"
brew "poetry"
brew "postgresql"
# Linux ps command can not be imported to OSX, https://apple.stackexchange.com/questions/187783/can-i-use-gnu-ps-on-os-x
brew "psgrep"
brew "pstree"
brew "python3"  # for AWS tools and VSCode
brew "redis"
brew "ruby"
brew "ruby-build"
brew "saw"
brew "shellcheck"
brew "telnet"
brew "terraform"
brew "tmux"
brew "tree"
brew "volta"
brew "weaveworks/tap/eksctl"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh-syntax-highlighting"

cask "adobe-acrobat-reader"
cask "adobe-creative-cloud"
cask "adoptopenjdk"
cask "alfred"
cask "aws-vault"
cask "brave-browser"
cask "chromedriver"
cask "cocoapods"
cask "dash"
# cask "dbeaver-community"
cask "deepl"
cask "discord"
cask "diskwave"
cask "docker"
cask "fork"
cask "github"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "imageoptim"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kindle"
cask "little-snitch"
cask "micro-snitch"
cask "ngrok"
cask "onedrive"
cask "postman"
cask "robo-3t"
cask "slack"
cask "stoplight-studio"
cask "vagrant"
cask "vlc"
cask "wireshark"
cask "zoom"

mas "Bandwidth+", id: 490461369
mas "Cyberduck", id: 409222199
mas "Hex Fiend", id: 1342896380
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "The Unarchiver", id: 425424353
mas "Transporter", id: 1450874784
mas "Xcode", id: 497799835
