#!/bin/bash
set -eux

FORCE_FLAG=''
print_usage() {
  printf "Usage: Only -f(=force) option is allowed."
}
while getopts 'f' flag; do
  case "${flag}" in
    f) FORCE_FLAG='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

UBUNTU=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
DOTFILES=$( dirname "${UBUNTU}" )

# packages
if [ ! -z ${FORCE_FLAG} ];then
  sudo apt update
  sudo apt upgrade
fi
cat "${UBUNTU}/packages" | grep "^[^#;]" | xargs sudo apt install -y

# snaps
cat "${UBUNTU}/snaps" | grep "^[^#;]" | xargs sudo snap install --classic

# git
source "${DOTFILES}/bin/git/config"

# VSCode
VSCODE_USER_SETTING=~/.config/Code/User
source "${DOTFILES}/bin/vscode/config"
$HOME/.config/Code/User/settings.json