#!/bin/zsh
set -euxo

# force flag
FORCE_FLAG=''
print_usage() {
    printf "Usage: Only -f(=force) option is allowed"
}
while getopts 'f' flag; do
    case "${flag}" in
        f) FORCE_FLAG='true' ;;
        *) print_usage
        exit 1 ;;
    esac
done

MACOS=$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )
DOTFILES=$( dirname "$MACOS" )
. "$DOTFILES/lib/colors"
APPLICATIONS="$DOTFILES/applications"

# install softwares
brew update
brew bundle --file="$MACOS/Brewfile"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# shell
if [ ! -z ${FORCE_FLAG} ];then
    sudo ln -f $MACOS/shell/shells /etc/shells
    chsh -s /bin/zsh
fi

yes | cp -afl "$APPLICATIONS/shell/bash/".* "$HOME/"
yes | cp -afl "$MACOS/shell/common/".* "$HOME/"
yes | cp -afl "$MACOS/shell/bash/".* "$HOME/"

# zsh
ZDOTDIR="$HOME/.zsh"
rm -rf "$ZDOTDIR"
mkdir -p "$ZDOTDIR"

yes | cp -afl "$APPLICATIONS/shell/zsh/.zsh/".* "$ZDOTDIR/"
yes | cp -afl "$MACOS/shell/zsh/.zsh/".* "$ZDOTDIR/"
ln -fns "$APPLICATIONS/shell/zsh/.zshenv" "$HOME/.zshenv"

ZSH_COMPLETIONS="/usr/local/share/zsh-completions"
mkdir -p "$ZSH_COMPLETIONS"
yes | cp -afl "$APPLICATIONS/shell/zsh/completion/"_* "$ZSH_COMPLETIONS/"

. "$HOME/.zshenv"

sudo chmod -R 755 /usr/local/share/zsh/site-functions   # https://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories

# karabiner
KARABINER_DIR="$HOME/.config/karabiner"
mkdir -p "$KARABINER_DIR"
ln -f "$APPLICATIONS/karabiner/karabiner.json" "$KARABINER_DIR/karabiner.json"

# OneDrive
HOST_NAME=$(uname -n)
MACHINE_NAME=${HOST_NAME%%.*}       # remove network name after .(dot)
ONEDRIVE_DIR=$HOME/OneDrive\ -\ $(whoami)
mkdir -p "${ONEDRIVE_DIR}/Images/Screenshots/$MACHINE_NAME"
defaults write com.apple.screencapture location "${ONEDRIVE_DIR}/screenshots/$MACHINE_NAME"

# tmux
ln -f "$APPLICATIONS/tmux/.tmux.conf" $HOME/.tmux.conf

# vim
ln -f "$APPLICATIONS/vim/.vimrc" $HOME/.vimrc

# VSCode
VSCODE_ZIP="VSCode-darwin-stable.zip"
code -h >/dev/null 2>&1 || wget 'https://go.microsoft.com/fwlink/?LinkID=620882' -O "$VSCODE_ZIP" && unzip "$VSCODE_ZIP" && rm -f "$VSCODE_ZIP" && mv "Visual Studio Code.app" /Applications && ln -fs "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" "/usr/local/bin/code"
VSCODE_USER_SETTING=$HOME/Library/Application\ Support/Code/User
mkdir -p "$VSCODE_USER_SETTING"
yes | cp -afl "$APPLICATIONS/vscode/User/". "${VSCODE_USER_SETTING}/"
cp -f "$APPLICATIONS/vscode/code" "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
source "$APPLICATIONS/vscode/setup"
/usr/local/bin/python3 -m pip install -r "$APPLICATIONS/vscode/python/requirements.txt"

echo "${GREEN}Packages are successfully installed!!!${NO_COLOR}"
