#!/bin/zsh
set -euxo

# force flag
FORCE_FLAG=''
print_usage() {
    printf "Usage: Only -f(=force) option is allowed"
}
while getopts 'f' flag; do
    case "${flag}" in
        f) FORCE_FLAG='true' ;;
        *) print_usage
        exit 1 ;;
    esac
done

MACOS=$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )
DOTFILES=$( dirname "$MACOS" )
. "$DOTFILES/lib/colors"
APPLICATIONS="$DOTFILES/applications"

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# shell
if [ ! -z ${FORCE_FLAG} ];then
    sudo ln -f $MACOS/shell/shells /etc/shells
    chsh -s /bin/zsh
fi

yes | cp -afl "$APPLICATIONS/shell/bash/".* "$HOME/"
yes | cp -afl "$MACOS/shell/common/".* "$HOME/"
yes | cp -afl "$MACOS/shell/bash/".* "$HOME/"

# zsh
ZDOTDIR="$HOME/.zsh"
rm -rf "$ZDOTDIR"
mkdir -p "$ZDOTDIR"

yes | cp -afl "$APPLICATIONS/shell/zsh/.zsh/".* "$ZDOTDIR/"
yes | cp -afl "$MACOS/shell/zsh/.zsh/".* "$ZDOTDIR/"
ln -fns "$APPLICATIONS/shell/zsh/.zshenv" "$HOME/.zshenv"

ZSH_COMPLETIONS="/usr/local/share/zsh-completions"
mkdir -p "$ZSH_COMPLETIONS"
yes | cp -afl "$APPLICATIONS/shell/zsh/completion/"_* "$ZSH_COMPLETIONS/"

. "$HOME/.zshenv"

sudo chmod -R 755 /usr/local/share/zsh/site-functions   # https://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories

# karabiner
KARABINER_DIR="$HOME/.config/karabiner"
mkdir -p "$KARABINER_DIR"
ln -f "$APPLICATIONS/karabiner/karabiner.json" "$KARABINER_DIR/karabiner.json"

# OneDrive
HOST_NAME=$(uname -n)
MACHINE_NAME=${HOST_NAME%%.*}       # remove network name after .(dot)
ONEDRIVE_DIR=$HOME/OneDrive\ -\ $(whoami)
mkdir -p "${ONEDRIVE_DIR}/Images/Screenshots/$MACHINE_NAME"
defaults write com.apple.screencapture location "${ONEDRIVE_DIR}/screenshots/$MACHINE_NAME"
