#!/bin/bash

# Check disk number of SD Card by `diskutil list`
DISK_N=${1:-"/dev/disk2"}

IMAGE=${2:-"2020-02-13-raspbian-buster-full.img"}
BLOCK_SIZE=${3:-"1M"}

RASPBIAN=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

diskutil unmountDisk "$DISK_N"
sudo dd bs="$BLOCK_SIZE" if="$RASPBIAN/images/$IMAGE" of="$DISK_N" conv=sync

# ex. 7323254784 bytes (7.3 GB, 6.8 GiB) copied, 3732.48 s, 2.0 MB/s = 約1時間かかる

# References
# https://www.raspberrypi.org/documentation/installation/installing-images/mac.md
